import type { CurriculumDay } from './types';

/**
 * 15-Day Production Curriculum: Full-Stack Software Engineering
 * Focus: Git Branching, PostgreSQL RLS Schema, REST APIs, State Management, CI/CD, and Cloud Deployment
 */
export const CODING_FULLSTACK_15_DAY_CURRICULUM: CurriculumDay[] = [
  // Sprint 1: Days 1-5 (Fundamentals & Architecture Drills)
  {
    day_number: 1,
    title: 'Day 01: Git Workflow, Dev Environment & Initial Commit',
    description: 'Set up development workspace, initialize strict TypeScript configuration, configure ESLint/Prettier, and open your initial feature branch PR.',
    instructions: 'Submit a GitHub repository or Pull Request link with clean branch structure and passing baseline checks.',
    starter_files_url: 'https://github.com/procuthub/starter-fullstack-template',
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: true,
  },
  {
    day_number: 2,
    title: 'Day 02: Relational Modeling & Row-Level Security (RLS)',
    description: 'Design 3NF relational schema in PostgreSQL, create migration scripts, and enforce strict Row-Level Security policies with zero data leak vectors.',
    instructions: 'Submit migration SQL files or PR link implementing user-scoped access control policies.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 3,
    title: 'Day 03: Scalable REST APIs & Request Validation',
    description: 'Build idempotent API endpoints with comprehensive schema validation (Zod), standardized HTTP status codes, and centralized error logging.',
    instructions: 'Submit a PR with tested CRUD endpoints and schema validation unit tests.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 4,
    title: 'Day 04: Frontend State Architecture & Optimistic UI',
    description: 'Implement modern client state management, optimistic mutation rollbacks, and query caching with zero-flicker re-renders.',
    instructions: 'Submit your interactive React/TypeScript component PR featuring optimistic feedback.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 5,
    title: 'Day 05: Sprint 1 Milestone — Core Module Review & PR Review',
    description: 'Consolidate Days 1–4 into an end-to-end working module with full automated test coverage and documentation.',
    instructions: 'Submit a clean PR for mentor architectural code review and leaderboard grading.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 48,
    is_published: false,
  },

  // Sprint 2: Days 6-10 (Production Architecture & Scalability)
  {
    day_number: 6,
    title: 'Day 06: Authentication & Role-Based Access Control (RBAC)',
    description: 'Implement secure JWT auth session lifecycle, route guards, token refreshing, and admin/student role boundaries.',
    instructions: 'Deliver auth guard implementation PR protecting private student resources.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 7,
    title: 'Day 07: Payment Gateway Webhooks & Idempotent Handlers',
    description: 'Integrate payment verification (Razorpay/Stripe), verify HMAC cryptographic signatures, and implement atomic transaction ledgers.',
    instructions: 'Submit webhook handler PR with signature verification and replay protection.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 8,
    title: 'Day 08: Background Queue Workers & Asynchronous Jobs',
    description: 'Decouple heavy tasks (video metadata parsing, batch email/WhatsApp notifications) into an async queue with exponential backoff retries.',
    instructions: 'Submit background worker PR with retry resilience and failure dead-letter handling.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 9,
    title: 'Day 09: Automated Testing Suites & CI/CD Pipelines',
    description: 'Author unit and integration tests using Vitest/Jest, and write a GitHub Actions workflow that blocks failing builds and linter warnings.',
    instructions: 'Submit a green CI/CD pipeline run link with 100% test pass confirmation.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 10,
    title: 'Day 10: Sprint 2 Milestone — Mid-Term Architecture Audit',
    description: 'Comprehensive codebase audit focusing on security vulnerabilities, query performance, and test coverage metrics.',
    instructions: 'Submit your completed mid-term refactoring PR for senior mentor grading.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 48,
    is_published: false,
  },

  // Sprint 3: Days 11-15 (Capstone Project & Cloud Deployment)
  {
    day_number: 11,
    title: 'Day 11: Production Capstone — Scaffolding & System Design',
    description: 'Architect the multi-tenant Capstone platform: define entity-relationship models, API contracts, and high-level architectural blueprint.',
    instructions: 'Submit your Capstone repository architecture design document and schema PR.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 12,
    title: 'Day 12: Production Capstone — Resilient Business Logic',
    description: 'Implement core business transactions, rate limiters, error boundaries, and fail-closed security guards.',
    instructions: 'Submit Capstone core logic PR with edge-case validation suites.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 13,
    title: 'Day 13: Production Capstone — Database Optimization & Caching',
    description: 'Add composite B-Tree indexes, analyze query execution plans with EXPLAIN ANALYZE, and introduce memory cache layers.',
    instructions: 'Submit PR showing measured query latency improvements and index migrations.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 14,
    title: 'Day 14: Production Capstone — Cloud Deployment & Live URL',
    description: 'Deploy the fullstack application to production cloud infrastructure (Vercel, Cloud Run, Supabase) with SSL, CDN, and health telemetry.',
    instructions: 'Submit your live deployment URL, GitHub repository link, and production release notes.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'github_pr',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 15,
    title: 'Day 15: Graduation, Technical Defense & Certificate Release',
    description: 'Present your production codebase in a technical defense review, complete the exit evaluation, and receive your verifiable credential.',
    instructions: 'Complete final technical defense submission and claim your verifiable Internship Certificate.',
    starter_files_url: null,
    track_type: 'coding',
    submission_type: 'text',
    deadline_hours: 24,
    is_published: false,
  },
];

