import type { CurriculumDay } from './types';

/**
 * 15-Day Production Curriculum: Motion Graphics & 3D Animation
 * Focus: After Effects, Cinema 4D/Blender, Kinetic Typography, 3D Tracking, PBR Materials, and Commercial Motion Reel
 */
export const MOTION_GRAPHICS_15_DAY_CURRICULUM: CurriculumDay[] = [
  // Sprint 1: Days 1-5 (Fundamentals & Kinetic Animation)
  {
    day_number: 1,
    title: 'Day 01: Workspace Setup, Keyframe Curves & Velocity',
    description: 'Master temporal and spatial easing in the Graph Editor, understand value curves, and produce smooth secondary motion.',
    instructions: 'Submit an animation test exhibiting easing, anticipation, and follow-through.',
    starter_files_url: 'https://drive.google.com/drive/folders/sample-motion-day-1',
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: true,
  },
  {
    day_number: 2,
    title: 'Day 02: Kinetic Typography & Expression-Driven Titles',
    description: 'Animate kinetic title systems with tracking animators, expression-based overshoot (inertia bounce), and voice cadence sync.',
    instructions: 'Submit a 15-second kinetic typography promo synced to a spoken word soundbite.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 3,
    title: 'Day 03: Vector Morphing & Shape Layer Rigging',
    description: 'Build responsive icon animations using trim paths, shape merge paths, repeater arrays, and null hierarchy controllers.',
    instructions: 'Submit an animated vector icon set with seamless state transitions.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 4,
    title: 'Day 04: Brand Logo Stings & Seamless Motion Loops',
    description: 'Create an energetic 5-second brand identity reveal utilizing alpha track mattes, particle accents, and looping geometries.',
    instructions: 'Deliver a high-impact animated logo bumper with transparent alpha or black background.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 5,
    title: 'Day 05: Sprint 1 Milestone — Dynamic Commercial Motion Bumper',
    description: 'Combine kinetic typography, shape morphs, and logo stings into a polished 15-second broadcast/social commercial teaser.',
    instructions: 'Submit your Sprint 1 motion export for live mentor critique and portfolio review.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 48,
    is_published: false,
  },

  // Sprint 2: Days 6-10 (3D Space, Blender/C4D & Camera Tracking)
  {
    day_number: 6,
    title: 'Day 06: Cinema 4D / Blender Integration & 3D Camera Tracking',
    description: 'Solve real-world video footage tracks, extract 3D point clouds, and composite 3D geometric objects seamlessly into live video.',
    instructions: 'Submit a camera-tracked composite video with shadow catcher and realistic perspective.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 7,
    title: 'Day 07: PBR Shading, Studio Lighting & Depth Passes',
    description: 'Set up three-point studio lighting rigs, apply realistic roughness/metallic PBR maps, and render out multi-channel EXR depth passes.',
    instructions: 'Submit high-resolution beauty pass and depth-of-field composite render.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 8,
    title: 'Day 08: Particle Dynamics & Abstract Mograph Simulation',
    description: 'Utilize procedural emitters, turbulence fields, and particle collision dynamics to create abstract sci-fi/organic motion simulations.',
    instructions: 'Submit a 10-second looping abstract particle simulation cut.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 9,
    title: 'Day 09: UI/UX Micro-Interactions & 3D Device Mockups',
    description: 'Animate mobile/desktop UI mockups floating in 3D isometric space with interactive clicks, gestures, and glass refraction.',
    instructions: 'Deliver a sleek SaaS software or mobile app product walkthrough video.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 10,
    title: 'Day 10: Sprint 2 Milestone — Mid-Term Commercial Reel Review',
    description: 'Consolidated commercial motion sequence combining 3D product renders, dynamic camera moves, and kinetic graphic accents.',
    instructions: 'Submit your mid-term commercial reel segment for mentor scoring and cohort ranking.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 48,
    is_published: false,
  },

  // Sprint 3: Days 11-15 (Capstone Project & Showreel Master)
  {
    day_number: 11,
    title: 'Day 11: Motion Capstone — 3D Styleframes & Storyboard Deck',
    description: 'Design 5 cohesive production styleframes, visual moodboards, and animatic timings for your final client commercial capstone.',
    instructions: 'Submit your styleframe presentation deck and rough animatic sequence.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 12,
    title: 'Day 12: Motion Capstone — 3D Scene Animation & Camera Blocking',
    description: 'Animate core product hero shots, keyframe dynamic camera swoops, and lock scene transition cuts to audio stems.',
    instructions: 'Submit rough playblast / hardware preview of the complete 3D scene timing.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 13,
    title: 'Day 13: Motion Capstone — Compositing, Grain & Color Finishing',
    description: 'Assemble multi-pass EXR renders in After Effects, add chromatic aberration, glow falls, 35mm film grain, and lens flares.',
    instructions: 'Submit near-final composite master cut for preliminary mentor feedback.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 14,
    title: 'Day 14: Final Capstone Master Export & Breakdown Reel',
    description: 'Render the final 4K master export alongside a behind-the-scenes breakdown reel revealing wireframes, depth passes, and layers.',
    instructions: 'Submit your completed 4K final export link with breakdown commentary.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'drive_link',
    deadline_hours: 24,
    is_published: false,
  },
  {
    day_number: 15,
    title: 'Day 15: Graduation, Exit Evaluation & Letter of Recommendation',
    description: 'Final mentor portfolio review, showreel cataloging, and release of your verified Internship Certificate.',
    instructions: 'Complete exit assessment and receive your digital verifiable certification.',
    starter_files_url: null,
    track_type: 'non_coding',
    submission_type: 'text',
    deadline_hours: 24,
    is_published: false,
  },
];

