import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, Check, ChevronDown, Clock3, LogOut, Menu, Play, Search, Sparkles, X } from 'lucide-react';
import { useAuth } from '../context/useAuth';
import { getStudentCourseData, listLessonResources, markLessonComplete, type Lesson, type LessonResource, type Module, type StudentCourseData } from '../lib/courseService';
import { AssignmentPanel, EnrollmentPanel, MilestonePanel } from '../components/StudentFlowPanels';

const emptyCourse: StudentCourseData = { cohort: null, modules: [], progress: [] };

export function StudentDashboard() {
  const { user, profile, signOut } = useAuth();
  const [course, setCourse] = useState<StudentCourseData>(emptyCourse);
  const [selectedLessonId, setSelectedLessonId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    if (!user) return;
    let active = true;
    getStudentCourseData(user.id).then((data) => {
      if (!active) return;
      setCourse(data);
      setSelectedLessonId(data.modules[0]?.lessons[0]?.id ?? null);
    }).catch((fetchError: Error) => active && setError(fetchError.message)).finally(() => active && setLoading(false));
    return () => { active = false; };
  }, [user, refreshKey]);

  const allLessons = useMemo(() => course.modules.flatMap((module) => module.lessons), [course.modules]);
  const selectedLesson = allLessons.find((lesson) => lesson.id === selectedLessonId) ?? null;
  const completedIds = new Set(course.progress.filter((item) => item.completed).map((item) => item.lesson_id));
  const completedCount = allLessons.filter((lesson) => completedIds.has(lesson.id)).length;
  const progressPercent = allLessons.length ? Math.round((completedCount / allLessons.length) * 100) : 0;
  const selectLesson = (lesson: Lesson) => { setSelectedLessonId(lesson.id); setSidebarOpen(false); };

  const toggleComplete = async () => {
    if (!user || !selectedLesson) return;
    const completed = !completedIds.has(selectedLesson.id);
    try {
      await markLessonComplete(user.id, selectedLesson.id, completed);
      setCourse((current) => ({ ...current, progress: [...current.progress.filter((item) => item.lesson_id !== selectedLesson.id), { lesson_id: selectedLesson.id, completed }] }));
    } catch (updateError) { setError(updateError instanceof Error ? updateError.message : 'Unable to update lesson progress.'); }
  };

  return <div className="min-h-screen bg-[#f6f7f9] text-slate-900">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex h-[73px] max-w-[1440px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><button onClick={() => setSidebarOpen(true)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 lg:hidden" aria-label="Open course navigation"><Menu size={21} /></button><div className="flex size-9 items-center justify-center rounded-xl bg-slate-950 text-white"><Sparkles size={18} /></div><div><p className="text-sm font-black tracking-tight text-slate-950">CUT / CRAFT</p><p className="hidden text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400 sm:block">Student studio</p></div></div><div className="flex items-center gap-3">{profile?.role === 'admin' && <Link to="/admin/courses" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800">Admin Courses</Link>}<div className="hidden items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 sm:flex"><div className="flex size-7 items-center justify-center rounded-full bg-orange-100 text-xs font-bold text-orange-700">{profile?.full_name?.charAt(0) ?? 'S'}</div><span className="max-w-32 truncate text-sm font-semibold">{profile?.full_name ?? 'Student'}</span></div><button onClick={signOut} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-900" aria-label="Sign out"><LogOut size={18} /></button></div></div></header>
    <div className="mx-auto flex max-w-[1440px]">
      <aside className={`${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 w-80 border-r border-slate-200 bg-white transition-transform lg:sticky lg:top-[73px] lg:block lg:h-[calc(100vh-73px)] lg:translate-x-0`}><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-orange-500">Your curriculum</p><h2 className="mt-1 text-lg font-black text-slate-950">{course.cohort?.name ?? 'Course workspace'}</h2></div><button onClick={() => setSidebarOpen(false)} className="p-2 text-slate-400 lg:hidden" aria-label="Close course navigation"><X size={19} /></button></div><div className="border-b border-slate-100 px-6 py-5"><div className="mb-2 flex justify-between text-xs font-bold"><span className="text-slate-500">Overall progress</span><span className="text-orange-600">{progressPercent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange-500 transition-all" style={{ width: `${progressPercent}%` }} /></div><p className="mt-2 text-xs text-slate-400">{completedCount} of {allLessons.length} lessons complete</p></div><nav className="max-h-[calc(100vh-240px)] overflow-y-auto p-4">{loading ? <SidebarSkeleton /> : course.modules.length ? course.modules.map((module) => <ModuleNav key={module.id} module={module} completedIds={completedIds} selectedLessonId={selectedLessonId} onSelect={selectLesson} />) : <EmptyState label="Your lessons will appear here once you are enrolled." />}</nav></aside>
      {sidebarOpen && <button className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close navigation overlay" />}
      <main className="min-w-0 flex-1 px-5 py-7 lg:px-10 lg:py-10"><div className="mx-auto max-w-5xl"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-bold text-orange-500">Keep building your edge</p><h1 className="text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Welcome back, {profile?.full_name?.split(' ')[0] ?? 'editor'}.</h1><p className="mt-2 text-slate-500">Pick up where you left off and keep your creative momentum moving.</p></div><button className="flex w-fit items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm hover:border-slate-300"><Search size={17} /> Search lessons</button></div>{error && <div className="mb-6 flex items-center justify-between rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>Couldn&apos;t load your course: {error}</span><button onClick={() => setError(null)} aria-label="Dismiss error"><X size={16} /></button></div>}{loading ? <PlayerSkeleton /> : course.cohort ? selectedLesson ? <LessonPlayer lesson={selectedLesson} completed={completedIds.has(selectedLesson.id)} onToggleComplete={toggleComplete} /> : <EmptyState label="No lessons have been published for this cohort yet." large /> : user && <EnrollmentPanel userId={user.id} onEnrolled={() => setRefreshKey((key) => key + 1)} />}{course.cohort && <><section className="mt-8 grid gap-4 sm:grid-cols-3"><StatCard icon={<BookOpen size={19} />} label="Lessons completed" value={`${completedCount}/${allLessons.length}`} /><StatCard icon={<Clock3 size={19} />} label="Learning time" value="Keep going" /><StatCard icon={<Sparkles size={19} />} label="Current streak" value="0 days" /></section><MilestonePanel progressPercent={progressPercent} completedCount={completedCount} totalLessons={allLessons.length} />{user && <AssignmentPanel userId={user.id} cohortId={course.cohort.id} />}</>}</div></main>
    </div>
  </div>;
}

function ModuleNav({ module, completedIds, selectedLessonId, onSelect }: { module: Module; completedIds: Set<string>; selectedLessonId: string | null; onSelect: (lesson: Lesson) => void }) { return <div className="mb-5"><div className="mb-2 flex items-center justify-between px-2 text-[11px] font-black uppercase tracking-wider text-slate-400"><span>{module.title}</span><ChevronDown size={14} /></div><div className="space-y-1">{module.lessons.map((lesson) => <button key={lesson.id} onClick={() => onSelect(lesson)} className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition ${lesson.id === selectedLessonId ? 'bg-orange-50 text-orange-700' : 'text-slate-600 hover:bg-slate-50'}`}><span className={`mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full border text-[10px] ${completedIds.has(lesson.id) ? 'border-emerald-500 bg-emerald-500 text-white' : lesson.id === selectedLessonId ? 'border-orange-300' : 'border-slate-200'}`}>{completedIds.has(lesson.id) && <Check size={12} />}</span><span className="text-sm font-semibold leading-5">{lesson.title}</span></button>)}</div></div>; }
function LessonPlayer({ lesson, completed, onToggleComplete }: { lesson: Lesson; completed: boolean; onToggleComplete: () => void }) {
  const [activeTab, setActiveTab] = useState<'overview' | 'resources' | 'qa'>('overview');
  const [resources, setResources] = useState<LessonResource[]>([]);
  const tabs = [{ id: 'overview' as const, label: 'Overview' }, { id: 'resources' as const, label: 'Resources' }, { id: 'qa' as const, label: 'Lesson Q&A' }];
  useEffect(() => { void listLessonResources(lesson.id).then(setResources); }, [lesson.id]);
  return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_40px_rgba(15,23,42,0.06)]"><div className="relative flex aspect-video items-center justify-center overflow-hidden bg-slate-950">{lesson.video_url ? <video className="absolute inset-0 size-full object-cover" controls src={lesson.video_url} /> : <><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(249,115,22,0.28),transparent_32%),linear-gradient(135deg,#111827,#020617)]" /><div className="relative flex size-16 items-center justify-center rounded-full bg-white text-slate-950 shadow-2xl"><Play size={25} fill="currentColor" className="ml-1" /></div></>}<span className="absolute bottom-4 left-5 rounded-md bg-black/40 px-2 py-1 text-xs font-bold text-white backdrop-blur">Lesson {lesson.position}</span></div><div className="p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-orange-500">Now learning</p><h2 className="text-2xl font-black tracking-tight text-slate-950">{lesson.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{lesson.description ?? 'A focused lesson to help you sharpen your editing instincts and make stronger creative decisions.'}</p></div><button onClick={onToggleComplete} className={`h-fit shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold transition ${completed ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-950 text-white hover:bg-orange-600'}`}>{completed ? <span className="flex items-center gap-2"><Check size={16} /> Completed</span> : 'Mark complete'}</button></div><div className="mt-8 flex gap-6 border-b border-slate-100 text-sm font-bold">{tabs.map((tab) => <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`${activeTab === tab.id ? 'border-b-2 border-orange-500 text-orange-600' : 'text-slate-400'} pb-3`}>{tab.label}</button>)}</div><div className="min-h-20 pt-5 text-sm leading-7 text-slate-600">{activeTab === 'overview' && <p>Watch the lesson, take a few notes, and apply the idea in your next edit. Your progress is saved to your student profile when you mark the lesson complete.</p>}{activeTab === 'resources' && (resources.length ? <div className="space-y-2">{resources.map((resource) => <a key={resource.id} href={resource.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 font-semibold text-slate-700 hover:border-orange-300 hover:text-orange-600"><span>{resource.name}</span><span aria-hidden="true">↗</span></a>)}</div> : <p className="text-slate-400">No downloadable resources have been added to this lesson yet.</p>)}{activeTab === 'qa' && <p className="text-slate-400">Be the first to ask a question about this lesson.</p>}</div></div></article>;
}
function StatCard({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex size-9 items-center justify-center rounded-lg bg-orange-50 text-orange-600">{icon}</div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p></div>; }
function EmptyState({ label, large = false }: { label: string; large?: boolean }) { return <div className={`rounded-2xl border border-dashed border-slate-300 bg-white text-center ${large ? 'px-6 py-24' : 'px-4 py-8'}`}><BookOpen className="mx-auto mb-3 text-slate-300" size={large ? 30 : 22} /><p className="mx-auto max-w-xs text-sm text-slate-500">{label}</p></div>; }
function SidebarSkeleton() { return <div className="space-y-5">{[1, 2, 3].map((item) => <div key={item} className="space-y-3"><div className="h-3 w-24 animate-pulse rounded bg-slate-100" /><div className="h-11 animate-pulse rounded-xl bg-slate-50" /><div className="h-11 animate-pulse rounded-xl bg-slate-50" /></div>)}</div>; }
function PlayerSkeleton() { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="aspect-video animate-pulse bg-slate-200" /><div className="space-y-4 p-8"><div className="h-3 w-24 animate-pulse rounded bg-slate-100" /><div className="h-8 w-2/3 animate-pulse rounded bg-slate-100" /><div className="h-4 w-full animate-pulse rounded bg-slate-100" /></div></div>; }