import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT_DIR = process.cwd();
const MIGRATIONS_DIR = path.join(ROOT_DIR, 'supabase', 'migrations');
const BOOTSTRAP_OUTPUT = path.join(ROOT_DIR, 'supabase', 'bootstrap_complete_schema.sql');
const MANIFEST_OUTPUT = path.join(ROOT_DIR, 'supabase', 'migrations_manifest.json');

interface MigrationMetadata {
  order: number;
  filename: string;
  sha256: string;
  sizeBytes: number;
  hasSecurityDefinerWithoutSearchPath: boolean;
  tableCreations: string[];
  rpcDefinitions: string[];
}

export function analyzeMigrations(): {
  migrations: MigrationMetadata[];
  totalFiles: number;
  bundledSql: string;
} {
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    throw new Error(`Migrations directory not found at: ${MIGRATIONS_DIR}`);
  }

  const files = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f: string) => f.endsWith('.sql'))
    .sort();

  if (files.length === 0) {
    throw new Error('No .sql migration files found in supabase/migrations/');
  }

  const migrations: MigrationMetadata[] = [];
  const header = [
    '-- ==============================================================================',
    '-- AUTOGENERATED CANONICAL DATABASE BOOTSTRAP SCRIPT',
    '-- Target: CUT / CRAFT Video Editing Cohort Platform',
    `-- Generated: ${new Date().toISOString()}`,
    `-- Migration Count: ${files.length} canonical migrations`,
    '-- Idempotent: Can be safely executed on empty or existing PostgreSQL databases',
    '-- ==============================================================================\n',
    '-- Ensure Required PostgreSQL Extensions',
    'create extension if not exists "uuid-ossp";',
    'create extension if not exists "pgcrypto";\n\n',
  ].join('\n');

  const bundledParts: string[] = [header];

  files.forEach((file: string, idx: number) => {
    const fullPath = path.join(MIGRATIONS_DIR, file);
    const content = fs.readFileSync(fullPath, 'utf-8');

    // SHA256 checksum
    const sha256 = crypto.createHash('sha256').update(content).digest('hex');

    // Security definer search path check
    const secDefinerMatches = content.match(/security\s+definer/gi) || [];
    const searchPathMatches = content.match(/set\s+search_path\s*=\s*public/gi) || [];
    const hasSecurityDefinerWithoutSearchPath =
      secDefinerMatches.length > searchPathMatches.length;

    // Detect table creations
    const tableCreations: string[] = [];
    const tableRegex = /create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?([a-zA-Z0-9_]+)/gi;
    let match;
    while ((match = tableRegex.exec(content)) !== null) {
      tableCreations.push(match[1]);
    }

    // Detect RPC definitions
    const rpcDefinitions: string[] = [];
    const rpcRegex = /create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?([a-zA-Z0-9_]+)/gi;
    while ((match = rpcRegex.exec(content)) !== null) {
      rpcDefinitions.push(match[1]);
    }

    migrations.push({
      order: idx + 1,
      filename: file,
      sha256,
      sizeBytes: Buffer.byteLength(content, 'utf-8'),
      hasSecurityDefinerWithoutSearchPath,
      tableCreations: Array.from(new Set(tableCreations)),
      rpcDefinitions: Array.from(new Set(rpcDefinitions)),
    });

    bundledParts.push(
      `-- ==============================================================================\n` +
        `-- Migration ${idx + 1}/${files.length}: ${file}\n` +
        `-- Checksum (SHA-256): ${sha256}\n` +
        `-- ==============================================================================\n\n` +
        content.trim() +
        '\n\n'
    );
  });

  return {
    migrations,
    totalFiles: files.length,
    bundledSql: bundledParts.join(''),
  };
}

function main() {
  const isWriteMode = process.argv.includes('--write');
  console.log('🔍 Analyzing Supabase migrations consistency...');

  const { migrations, totalFiles, bundledSql } = analyzeMigrations();

  console.log(`✅ Discovered ${totalFiles} sequential canonical migrations:`);
  migrations.forEach((m: MigrationMetadata) => {
    const flags: string[] = [];
    if (m.tableCreations.length > 0) flags.push(`Tables: [${m.tableCreations.join(', ')}]`);
    if (m.rpcDefinitions.length > 0) flags.push(`RPCs: ${m.rpcDefinitions.length}`);
    console.log(`  [${String(m.order).padStart(2, '0')}] ${m.filename} (${m.sizeBytes} bytes) ${flags.length ? `-> ${flags.join(' | ')}` : ''}`);
  });

  if (isWriteMode || process.argv.includes('--generate')) {
    console.log(`\n📦 Writing consolidated bootstrap file to: ${path.relative(ROOT_DIR, BOOTSTRAP_OUTPUT)}`);
    fs.writeFileSync(BOOTSTRAP_OUTPUT, bundledSql, 'utf-8');

    console.log(`📋 Writing migrations manifest to: ${path.relative(ROOT_DIR, MANIFEST_OUTPUT)}`);
    fs.writeFileSync(
      MANIFEST_OUTPUT,
      JSON.stringify(
        {
          version: '1.0.0',
          generatedAt: new Date().toISOString(),
          migrationCount: totalFiles,
          migrations,
        },
        null,
        2
      ),
      'utf-8'
    );

    console.log('✨ Bootstrap script and manifest successfully generated!');
  } else {
    console.log('\n💡 Pass --write to generate supabase/bootstrap_complete_schema.sql and migrations_manifest.json');
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

